# Generated by Django 4.2.13 on 2026-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='atributos',
            field=models.JSONField(blank=True, default=dict, help_text='Especificações técnicas livres em formato chave-valor (JSONB).'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de palavras-chave para categorização e busca.'),
        ),
    ]
